# Evidence Link Auditor Script
# Validates external links, internal links, and unresolved markers in bot-output/outputs

param(
    [string]$OutputRoot = "bot-output/outputs",
    [string]$ReportPath = "bot-output/outputs/2026-03-01-qa/evidence-audit.md"
)

$ErrorActionPreference = "Continue"
$auditResults = @{
    TotalFiles = 0
    ExternalLinks = @{ Total = 0; Valid = 0; Invalid = 0; Details = @() }
    InternalLinks = @{ Total = 0; Valid = 0; Invalid = 0; Details = @() }
    UnresolvedMarkers = @{ Total = 0; Files = @() }
    PassFail = "PASS"
}

# Get all markdown files
$mdFiles = Get-ChildItem -Path $OutputRoot -Recurse -Filter "*.md" -File
$auditResults.TotalFiles = $mdFiles.Count

Write-Host "Scanning $($mdFiles.Count) markdown files..." -ForegroundColor Cyan

foreach ($file in $mdFiles) {
    $content = Get-Content $file.FullName -Raw
    $relativePath = $file.FullName.Replace((Get-Location).Path + "\", "")
    
    # Skip the audit report itself to avoid self-referential issues
    if ($relativePath -match 'evidence-audit\.md$') {
        continue
    }
    
    # Check for unresolved markers (exclude those in backticks/code blocks)
    # Remove content in backticks first to avoid false positives on documentation references
    $contentWithoutCode = $content -replace '`[^`]+`', '' -replace '```[\s\S]*?```', ''
    $markers = [regex]::Matches($contentWithoutCode, '\b(PENDING|TODO|TBD)\b')
    if ($markers.Count -gt 0) {
        $auditResults.UnresolvedMarkers.Total += $markers.Count
        $auditResults.UnresolvedMarkers.Files += @{
            Path = $relativePath
            Count = $markers.Count
            Markers = ($markers | ForEach-Object { $_.Value }) -join ", "
        }
        Write-Host "  [WARN] Unresolved markers in $relativePath : $($markers.Count)" -ForegroundColor Yellow
    }
    
    # Extract external links (http/https)
    $externalLinks = [regex]::Matches($content, 'https?://[^\s\)\]"]+')
    foreach ($match in $externalLinks) {
        $url = $match.Value
        $auditResults.ExternalLinks.Total++
        
        # Quick validation: check if URL looks valid
        if ($url -match '^https?://[a-zA-Z0-9]') {
            $auditResults.ExternalLinks.Valid++
            $auditResults.ExternalLinks.Details += @{
                File = $relativePath
                URL = $url
                Status = "VALID_FORMAT"
            }
        } else {
            $auditResults.ExternalLinks.Invalid++
            $auditResults.ExternalLinks.Details += @{
                File = $relativePath
                URL = $url
                Status = "INVALID_FORMAT"
            }
            $auditResults.PassFail = "FAIL"
        }
    }
    
    # Extract internal links (GitHub blob URLs pointing to same repo)
    $internalLinks = [regex]::Matches($content, 'https://github\.com/Dalomeve/bot-output/blob/main/[^\s\)\]"]+')
    foreach ($match in $internalLinks) {
        $url = $match.Value
        $auditResults.InternalLinks.Total++
        
        # Extract path from URL
        $pathPart = $url -replace 'https://github\.com/Dalomeve/bot-output/blob/main/', ''
        $pathPart = $pathPart -replace '#.*', ''  # Remove anchor
        
        # Check if referenced file exists in workspace
        # Try both direct path and bot-output/ prefixed path
        $fullPath = Join-Path (Get-Location) $pathPart
        $altPath = Join-Path (Get-Location) "bot-output/$pathPart"
        
        if (Test-Path $fullPath) {
            $auditResults.InternalLinks.Valid++
            $auditResults.InternalLinks.Details += @{
                File = $relativePath
                URL = $url
                Status = "EXISTS"
            }
        } elseif (Test-Path $altPath) {
            $auditResults.InternalLinks.Valid++
            $auditResults.InternalLinks.Details += @{
                File = $relativePath
                URL = $url
                Status = "EXISTS (bot-output/)"
            }
        } else {
            $auditResults.InternalLinks.Invalid++
            $auditResults.InternalLinks.Details += @{
                File = $relativePath
                URL = $url
                Status = "NOT_FOUND"
            }
            $auditResults.PassFail = "FAIL"
            Write-Host "  [WARN] Internal link not found: $pathPart" -ForegroundColor Yellow
        }
    }
}

# Generate report
$reportContent = @"
# Evidence Link Audit Report

**Audit Date:** $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")  
**Output Root:** $OutputRoot  
**Report Generated By:** evidence-link-auditor.ps1

---

## Summary

| Metric | Value |
|--------|-------|
| Total Files Scanned | $($auditResults.TotalFiles) |
| External Links | $($auditResults.ExternalLinks.Total) |
| - Valid | $($auditResults.ExternalLinks.Valid) |
| - Invalid | $($auditResults.ExternalLinks.Invalid) |
| Internal Links | $($auditResults.InternalLinks.Total) |
| - Valid | $($auditResults.InternalLinks.Valid) |
| - Invalid | $($auditResults.InternalLinks.Invalid) |
| Unresolved Markers | $($auditResults.UnresolvedMarkers.Total) |
| **Overall Status** | **$($auditResults.PassFail)** |

---

## External Links Validation

"@

if ($auditResults.ExternalLinks.Details.Count -gt 0) {
    $reportContent += "| File | URL | Status |`n"
    $reportContent += "|------|-----|--------|`n"
    foreach ($detail in $auditResults.ExternalLinks.Details) {
        $reportContent += "| $($detail.File) | $($detail.URL) | $($detail.Status) |`n"
    }
} else {
    $reportContent += "*No external links found.*`n"
}

$reportContent += @"

---

## Internal Links Validation

"@

if ($auditResults.InternalLinks.Details.Count -gt 0) {
    $reportContent += "| File | URL | Status |`n"
    $reportContent += "|------|-----|--------|`n"
    foreach ($detail in $auditResults.InternalLinks.Details) {
        $reportContent += "| $($detail.File) | $($detail.URL) | $($detail.Status) |`n"
    }
} else {
    $reportContent += "*No internal links found.*`n"
}

$reportContent += @"

---

## Unresolved Markers

"@

if ($auditResults.UnresolvedMarkers.Files.Count -gt 0) {
    $reportContent += "| File | Count | Markers |`n"
    $reportContent += "|------|-------|---------|`n"
    foreach ($file in $auditResults.UnresolvedMarkers.Files) {
        $reportContent += "| $($file.Path) | $($file.Count) | $($file.Markers) |`n"
    }
} else {
    $reportContent += "*No unresolved markers (PENDING, TODO, TBD) found.*`n"
}

$reportContent += @"

---

## Pass/Fail Criteria

- **PASS**: All external links have valid format, all internal links point to existing files, no unresolved markers
- **FAIL**: Any invalid external links, broken internal links, or unresolved markers present

**Current Status:** $($auditResults.PassFail)

---

*Audit completed: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")*
"@

# Write report
$reportDir = Split-Path $ReportPath -Parent
if (!(Test-Path $reportDir)) {
    New-Item -Path $reportDir -ItemType Directory -Force | Out-Null
}
$reportContent | Out-File -FilePath $ReportPath -Encoding UTF8

Write-Host "`nAudit complete. Report written to $ReportPath" -ForegroundColor Green
Write-Host "Status: $($auditResults.PassFail)" -ForegroundColor $(if ($auditResults.PassFail -eq "PASS") { "Green" } else { "Red" })

# Output results as JSON for programmatic access
$auditResults | ConvertTo-Json -Depth 5
